core/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import *


urlpatterns = [
    path('', main, name='main'),
    path('search/', search_student, name='search_student'),
    path('student/<int:pk>/', item_student, name='item_student'),
    path('student/<int:pk>/delete/', delete_student, name='delete_student'),
    path('student/create/', create_student, name='create_student'),
    path('student/<int:pk>/update/', UpdateStudent.as_view(), name='update_student'),

    path('login/', login_profile, name='login'),
    path('logout/', logout_profile, name='logout'),
    path('register/', register_profile, name='register'),
    path('profile/', profile, name='profile'),

    path('send_message/', send_message, name='send_message'),

    path('reset_password/', PasswordResetView.as_view(), name='reset_pasword'),
    path('reset_password_sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('ajax/get_groups_by_school/<int:pk>/', get_groups_by_school),
    path('ajax/create_school/<int:pk>/', create_group),
]   

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls'))
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

MALE = 'M'
FEMALE = 'F'

GENDERS = (
    (MALE, 'Мужской'),
    (FEMALE, 'Женский')
)


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата добавление') 
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата изменения')

    class Meta:
        abstract = True


class CustomAccountManager(BaseUserManager):
    
    def create_superuser(self, phone_number, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Суперпользователь должен быть назначен is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Суперпользователь должен быть назначен is_superuser=True.')

        return self.create_user(phone_number, password, **other_fields)

    def create_user(self, phone_number, password, **other_fields):

        user = self.model(phone_number=phone_number, **other_fields)
        user.set_password(password)
        user.save()
        return user


class Teacher(AbstractBaseUser, PermissionsMixin, TimeStampMixin):

    class Meta:
        verbose_name = "учитель"
        verbose_name_plural = 'учителя'
        ordering = ('-created_at', '-updated_at')

    avatar = models.ImageField(upload_to='avatars/', verbose_name='аватарка', null=True, blank=True)
    phone_number = models.CharField(max_length=10, verbose_name='номер телефона', unique=True)
    name = models.CharField(max_length=150, blank=True, verbose_name='полная имя')
    gender = models.CharField(max_length=1, verbose_name='пол', choices=GENDERS, default=MALE)
    email = models.EmailField(verbose_name='элетронная почта', null=True, blank=True)
    group = models.OneToOneField('Group', verbose_name='класс', 
                    on_delete=models.SET_NULL, null=True, related_name='set_teacher')
    
    is_staff = models.BooleanField(default=True, verbose_name='статус персонала')
    is_active = models.BooleanField(default=True, verbose_name='подтверждение по почте')
    is_superuser = models.BooleanField(default=False, verbose_name='cтатус администратора')
    objects = CustomAccountManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return f'{self.phone_number}'


class Student(TimeStampMixin):

    class Meta:
        verbose_name = 'ученик'
        verbose_name_plural = 'ученики'
        ordering = ('-created_at', '-updated_at')

    name = models.CharField(max_length=50, verbose_name='ФИО')
    email = models.EmailField(verbose_name='элетронная почта')
    birthday = models.DateField(verbose_name='дата рождения')
    group = models.ForeignKey('Group', verbose_name='класс', on_delete=models.SET_NULL, null=True,)
    address = models.CharField(max_length=50, verbose_name='адрес')
    gender = models.CharField(max_length=1, verbose_name='пол', choices=GENDERS, default=MALE)
    photo = models.ImageField(verbose_name='фото ученика', upload_to='students/', 
                                                                blank=True, null=True)
    is_active = models.BooleanField(default=False, verbose_name='подтверждение')                                                    

    def __str__(self):
        return f'{self.name}'


class Group(TimeStampMixin):

    class Meta:
        verbose_name = 'класс'
        verbose_name_plural = 'классы'
        ordering = ('-created_at', '-updated_at')
    
    title = models.CharField(max_length=15, verbose_name='название класса')
    teacher = models.OneToOneField('Teacher', verbose_name='классный руководитель', blank=True, 
                on_delete=models.SET_NULL, null=True, related_name='set_group', default=None)
    students = models.ManyToManyField('Student', verbose_name='ученики',
                                         blank=True, related_name='set_group')

    def __str__(self):
        return f'{self.title}'


class School(TimeStampMixin):
    
    class Meta:
        verbose_name = 'школа'
        verbose_name_plural = 'школы'
        ordering = ('-created_at', '-updated_at')

    title = models.CharField(max_length=50, verbose_name='название школы')
    groups = models.ManyToManyField('Group', verbose_name='классы', related_name='set_school', blank=True)

    def __str__(self):
        return f'{self.title}'
    

# Create your models here.

templates/student/create_student.html
{% extends 'base.html' %}

{% block title %}| Новый ученик{% endblock title %}

{% block content %}

    <div class="container">
        <h4 class="text-center">Новый ученик</h4>
        <form action="{% url 'create_student' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <h6><label for="id_name">{{ form.name.label }} <span class="text-danger">*</span></label></h6>
                {{ form.name }}
                {% if form.name.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.name.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_email">{{ form.email.label }} <span class="text-danger">*</span></label></h6>
                {{ form.email }}
                {% if form.email.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.email.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_birthday">{{ form.birthday.label }} <span class="text-danger">*</span></label></h6>
                {{ form.birthday }}
                {% if form.birthday.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.birthday.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_address">{{ form.address.label }} <span class="text-danger">*</span></label></h6>
                {{ form.address }}
                {% if form.address.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.address.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_gender">{{ form.gender.label }} <span class="text-danger">*</span></label></h6>
                {{ form.gender }}
                {% if form.gender.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.gender.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_photo">{{ form.photo.label }}</label></h6>
                {{ form.photo }}
                {% if form.photo.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.photo.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <input type="hidden" name="group" value="{{ request.user.group.id }}">
                <input type="submit" value="Добавить" class="btn btn-primary w-100">
            </div>
        </form>
    </div>

{% endblock content %}

templates/student/edit_student.html
{% extends 'base.html' %}

{% block title %}| Редактирование студенита {{ student.name }}{% endblock title %}

{% block content %}

    <div class="container">
        <h4 class="text-center">Редактирование ученика(цу) {{ student.name }}</h4>
        <form action="{% url 'update_student' pk=student.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <h6><label for="id_name">{{ form.name.label }} <span class="text-danger">*</span></label></h6>
                {{ form.name }}
                {% if form.name.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.name.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_email">{{ form.email.label }} <span class="text-danger">*</span></label></h6>
                {{ form.email }}
                {% if form.email.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.email.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_birthday">{{ form.birthday.label }} <span class="text-danger">*</span></label></h6>
                {{ form.birthday }}
                {% if form.birthday.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.birthday.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_address">{{ form.address.label }} <span class="text-danger">*</span></label></h6>
                {{ form.address }}
                {% if form.address.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.address.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_gender">{{ form.gender.label }} <span class="text-danger">*</span></label></h6>
                {{ form.gender }}
                {% if form.gender.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.gender.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <h6><label for="id_photo">Выбрать новую фотографию</label></h6>
                {{ form.photo }}
                {% if form.photo.errors %}<div class="alert alert-danger mt-3"><strong>{{ form.photo.errors }}</strong></div>{% endif %}
            </div>
            <div class="mb-3">
                <input type="hidden" name="group" value="{{ request.user.group.id }}">
                <input type="submit" value="Изменить" class="btn btn-primary w-100">
            </div>
        </form>
    </div>

{% endblock content %}

templates/student/student.html
{% extends 'base.html' %}
{% load static %}

{% block title %}| {{ student.name }}{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 mb-4"><h4 class="text-center">{{ student.name }}</h4></div>
            <div class="col-12 col-md-6 col-lg-4 mb-3">
                {% if student.photo %}
                    <img src="{{ student.photo.url }}" class="w-100" alt="">
                {% else %}
                    <img src="{% static 'img/unknown_student.png' %}" class="w-100" alt="">
                {% endif %}
            </div>
            <div class="col-12 col-md-6 col-lg-4 mb-3">
                <p><b>ФИО:</b> {{ student.name }}</p>
                <p><b>Элетронная почта:</b> {{ student.email }}</p>
                <p><b>Дата рождения:</b> {{ student.bithday }}</p>
                <p><b>Школа:</b> {{ student.group.set_school.all.0.title }}</p>
                <p><b>Класс:</b> {{ student.group.title }}</p>
                <p><b>Адрес:</b> {{ student.address }}</p>
                <p><b>Пол:</b> {{ student.get_gender_display  }}</p>
            </div>
        </div>
    </div>

    <div class="panel">
        <a href="{% url 'delete_student' pk=student.id %}" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></a>
        <a href="" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
        <a href="" class="btn btn-primary"><i class="fa-solid fa-envelope"></i></a>
    </div>

{% endblock content %}